
var manualSendResults = true;
function genCode()
{
    var chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    var c = "";
    for (var i = 0; i < 5; ++i) {
        var j = parseInt(Math.round(Math.random()*(chars.length-1)));
        c = chars[j] + c + chars[j];
    }
    return c;
}

var counterOverride = parseInt(Math.round(Math.random()*10000));

var practiceItemTypes = ["practice"];
var shuffleSequence = seq("__workerid__",seq(rshuffle("0-1", "0-3", "0-2", "0-4")), "__results__", "__code__");
define_ibex_controller({
    name: "AJ",

    jqueryWidget: {
        _init: function () {
            this.options.transfer = null; // Remove 'click to continue message'.
            this.element.VBox({
                options: this.options,
                triggers: [1],
                children: [
                    "Message", this.options,
                    "AcceptabilityJudgment", this.options,
                ]
            });
        }
    },

    properties: { }
});

var defaults = [
    "AJ", {
        presentAsScale: true,
        as: ["1", "2", "3", "4", "5", "6", "7"],
        audioMessage: "Click here to play audio",
        audioTrigger: "click"
    }
];var items = [

["__workerid__", "Form", { html: "<p>Please enter your worker id: <p><input type='text' name='workerid' size='20'>" }],

["__results__", "__SendResults__", { }],

["__code__", "Message", { transfer: null, html: "Thank you! Your completion code is: " + genCode() }],

[["0-1", 2], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>People lined up at the climate conference to see government officials. Everyone saw several well known politicians. Nancy felt specially happy because she saw some of the really high profile politicians.<br>Even Obama.", "leftComment": "completely unnatural"}],
[["0-2", 2], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>People lined up at the climate conference to see government officials. The line was too long, so each person got to meet only one official. Nancy felt happy because she saw the vice president, Joe Biden. But Bill, who was the last person in the line, got lucky he met someone really special! <br>Even Obama.", "leftComment": "completely unnatural"}],
[["0-3", 2], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>People lined up at the climate conference to see government officials. Everyone saw several well known politicians. Nancy felt specially happy because she saw some of the really high profile politicians.<br>Obama, even.", "leftComment": "completely unnatural"}],
[["0-4", 2], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>People lined up at the climate conference to see government officials. The line was too long, so each person got to meet only one official. Nancy felt happy because she saw the vice president, Joe Biden. But Bill, who was the last person in the line, got lucky he met someone really special! <br>Obama, even.", "leftComment": "completely unnatural"}],
[["0-1", 4], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>Everyone on the Dutch speed skating team won at least one medal. Mostly, people won bronze and silver medals. Mary did particularly well this year and won multiple medals. <br>Even a gold medal.", "leftComment": "completely unnatural"}],
[["0-2", 4], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>Every member of the Dutch speed skating team won exactly one medal: bronze, silver , or gold. Mary, the new member of the team, did particularly well and also ended up winning a medal. <br>Even a gold medal.", "leftComment": "completely unnatural"}],
[["0-3", 4], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>Everyone on the Dutch speed skating team won at least one medal. Mostly, people won bronze and silver medals. Mary did particularly well this year and won multiple medals. <br>A gold medal, even.", "leftComment": "completely unnatural"}],
[["0-4", 4], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>Every member of the Dutch speed skating team won exactly one medal: bronze, silver , or gold. Mary, the new member of the team, did particularly well and also ended up winning a medal. <br>A gold medal, even.", "leftComment": "completely unnatural"}],
[["0-1", 6], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>We were playing a card game where each player has five cards. The player with the highest card wins. Aces beat kings, kings beat queens, etc. In the end Sally asked whether I had a jack. I said I did. But in fact I had some better cards in my hand.<br>Even an ace.", "leftComment": "completely unnatural"}],
[["0-2", 6], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>We were playing a card game where each player gets only one card. Aces beat kings, kings beat queens, etc.  In the end Sally asked whether I had a jack. But I told her that in fact I had a higher card.  <br>Even an ace.", "leftComment": "completely unnatural"}],
[["0-3", 6], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>We were playing a card game where each player has five cards. The player with the highest card wins. Aces beat kings, kings beat queens, etc. In the end Sally asked whether I had a jack. I said I did. But in fact I had some better cards in my hand.<br>An ace, even.", "leftComment": "completely unnatural"}],
[["0-4", 6], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>We were playing a card game where each player gets only one card. Aces beat kings, kings beat queens, etc.  In the end Sally asked whether I had a jack. But I told her that in fact I had a higher card.  <br>An ace, even.", "leftComment": "completely unnatural"}],
[["0-1", 8], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>It\u2019s the international friendship day and in our school, each child is supposed to hug at least one other student. Alice has not been talking to, Isaac, for the past few months since he\u2019s her least favourite classmate. But today Alice hugged all of her classmates. <br>Even Isaac.", "leftComment": "completely unnatural"}],
[["0-2", 8], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>It\u2019s the children's reconciliation day at school and each child is supposed to choose one child and hug him/her. Alice had not been talking to Harry, Alfie, and Isaac for the past few months. She specially does not like Isaac. But today, she decided to hug someone she didn't normally talk to. Guess who she hugged!<br>Even Isaac.", "leftComment": "completely unnatural"}],
[["0-3", 8], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>It\u2019s the international friendship day and in our school, each child is supposed to hug at least one other student. Alice has not been talking to, Isaac, for the past few months since he\u2019s her least favourite classmate. But today Alice hugged all of her classmates. <br>Isaac, even.", "leftComment": "completely unnatural"}],
[["0-4", 8], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>It\u2019s the children's reconciliation day at school and each child is supposed to choose one child and hug him/her. Alice had not been talking to Harry, Alfie, and Isaac for the past few months. She specially does not like Isaac. But today, she decided to hug someone she didn't normally talk to. Guess who she hugged!<br>Isaac, even.", "leftComment": "completely unnatural"}],
[["0-1", 10], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>Every time the university senate meets, one student representative has to attend. This is not a popular task, and Sarah usually avoids it. This week, the meeting was going to be so interesting that many students ended up going. <br>Even Sarah.", "leftComment": "completely unnatural"}],
[["0-2", 10], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>Every time the university senate meets, one student representative has to attend. This is not a popular task, and Sarah usually avoids it. This week, the meeting was scheduled in the week of exams and it was really difficult to find the one student who could go. But guess who ended up going?<br>Even Sarah.", "leftComment": "completely unnatural"}],
[["0-3", 10], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>Every time the university senate meets, one student representative has to attend. This is not a popular task, and Sarah usually avoids it. This week, the meeting was going to be so interesting that many students ended up going. <br>Sarah, even. ", "leftComment": "completely unnatural"}],
[["0-4", 10], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>Every time the university senate meets, one student representative has to attend. This is not a popular task, and Sarah usually avoids it. This week, the meeting was scheduled in the week of exams and it was really difficult to find the one student who could go. But guess who ended up going?<br>Sarah, even. ", "leftComment": "completely unnatural"}],
[["0-1", 12], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>There was a professional marathon today where everyone who came within 5 minutes of the world record would win a prize of $5,000. A lot of athletes from all over the world took part. Many finished within this time.  <br>Even an amateur.", "leftComment": "completely unnatural"}],
[["0-2", 12], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>There was a professional marathon today where the winner would win $5,000. A lot of athletes from all over the world took part. This tournament is always very competitive. But you\u2019ll never believe who won the prize this year.<br>Even an amateur.", "leftComment": "completely unnatural"}],
[["0-3", 12], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>There was a professional marathon today where everyone who came within 5 minutes of the world record would win a prize of $5,000. A lot of athletes from all over the world took part. Many finished within this time.  <br>An amateur, even.", "leftComment": "completely unnatural"}],
[["0-4", 12], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>There was a professional marathon today where the winner would win $5,000. A lot of athletes from all over the world took part. This tournament is always very competitive. But you\u2019ll never believe who won the prize this year.<br>An amateur, even.", "leftComment": "completely unnatural"}],
[["0-1", 14], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>Every week in my physics class, the teacher asks a question which is usually very difficult and everyone who can answer it correctly wins extra credit. Peter, who is very bad at physics, hardly ever knows the answer. But in today's class, everyone gave the winning answer. <br>Even Peter.", "leftComment": "completely unnatural"}],
[["0-2", 14], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>Every week in my physics class, the teacher asks a question which is usually very difficult and whoever gives the right answer first, gets extra credit. Peter is very bad at physics and never knows the answer. This week, however, the question was not as difficult as usual, so it seemed that many people were getting at the answer. But guess who gave the winning answer!<br>Even Peter.", "leftComment": "completely unnatural"}],
[["0-3", 14], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>Every week in my physics class, the teacher asks a question which is usually very difficult and everyone who can answer it correctly wins extra credit. Peter, who is very bad at physics, hardly ever knows the answer. But in today's class, everyone gave the winning answer. <br>Peter, even.", "leftComment": "completely unnatural"}],
[["0-4", 14], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>Every week in my physics class, the teacher asks a question which is usually very difficult and whoever gives the right answer first, gets extra credit. Peter is very bad at physics and never knows the answer. This week, however, the question was not as difficult as usual, so it seemed that many people were getting at the answer. But guess who gave the winning answer!<br>Peter, even.", "leftComment": "completely unnatural"}],
[["0-1", 16], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>Previous studies on animal behavior had shown that unlike the majority of mammals, the nervous system of rats makes them incapable of dreaming like humans. More recent studies, however, suggest that in fact all mammals dream like humans.<br>Even rats.", "leftComment": "completely unnatural"}],
[["0-2", 16], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>Previous studies on animal behavior had shown that no species of animals is capable of dreaming like humans. More recent studies, however, suggest differently! It\u2019s proven that there is only one species that dreams like humans, and it\u2019s not monkeys or chimpanzees. I thought that these animals, due to the similar nervous system they have to humans, actually dream like humans. But guess what animals do!<br>Even rats.", "leftComment": "completely unnatural"}],
[["0-3", 16], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>Previous studies on animal behavior had shown that unlike the majority of mammals, the nervous system of rats makes them incapable of dreaming like humans. More recent studies, however, suggest that in fact all mammals dream like humans.<br>Rats, even.", "leftComment": "completely unnatural"}],
[["0-4", 16], "AJ", {"q": "Please select a number", "rightComment": "completely natural", "s": "How natural did you think the last line was given the context?", "html": "<br>Previous studies on animal behavior had shown that no species of animals is capable of dreaming like humans. More recent studies, however, suggest differently! It\u2019s proven that there is only one species that dreams like humans, and it\u2019s not monkeys or chimpanzees. I thought that these animals, due to the similar nervous system they have to humans, actually dream like humans. But guess what animals do!<br>Rats, even.", "leftComment": "completely unnatural"}]
];
