
var manualSendResults = true;
function genCode()
{
    var chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    var c = "";
    for (var i = 0; i < 5; ++i) {
        var j = parseInt(Math.round(Math.random()*(chars.length-1)));
        c = chars[j] + c + chars[j];
    }
    return c;
}

var counterOverride = parseInt(Math.round(Math.random()*10000));

var practiceItemTypes = ["practice"];
var shuffleSequence = seq("__workerid__",seq(rshuffle("0-1", "0-3", "0-2", "0-5", "0-4", "0-7", "0-6", "0-8")), "__results__", "__code__");
define_ibex_controller({
    name: "AJ",

    jqueryWidget: {
        _init: function () {
            this.options.transfer = null; // Remove 'click to continue message'.
            this.element.VBox({
                options: this.options,
                triggers: [1],
                children: [
                    "Message", this.options,
                    "AcceptabilityJudgment", this.options,
                ]
            });
        }
    },

    properties: { }
});

var defaults = [
    "AJ", {
        presentAsScale: true,
        as: ["1", "2", "3", "4", "5", "6", "7"],
        audioMessage: "Click here to play audio",
        audioTrigger: "click"
    }
];var items = [

["__workerid__", "Form", { html: "<p>Please enter your worker id: <p><input type='text' name='workerid' size='20'>" }],

["__results__", "__SendResults__", { }],

["__code__", "Message", { transfer: null, html: "Thank you! Your completion code is: " + genCode() }],

[["0-1", 2], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["notafriend.wav"]}, "html": "You are at a party and everyone is talking about Jenny. Someone asks you:<br>You're not a friend of Jenny's?<br>Yes, I'm a friend of Jenny's", "leftComment": "completely unnatural"}],
[["0-2", 2], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["notafriend.wav"]}, "html": "You are at a party and everyone is talking about Jenny. Someone asks you:<br>You're not a friend of Jenny's?<br>Yes, I'm not a friend of Jenny's", "leftComment": "completely unnatural"}],
[["0-3", 2], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["notafriend.wav"]}, "html": "You are at a party and everyone is talking about Jenny. Someone asks you:<br>You're not a friend of Jenny's?<br>No, I'm a friend of Jenny's.", "leftComment": "completely unnatural"}],
[["0-4", 2], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["notafriend.wav"]}, "html": "You are at a party and everyone is talking about Jenny. Someone asks you:<br>You're not a friend of Jenny's?<br>No, I'm not a friend of Jenny's", "leftComment": "completely unnatural"}],
[["0-5", 2], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["areafriend.wav"]}, "html": "You are at a party and everyone is talking about Jenny. Someone asks you:<br>You're a friend of Jenny's?<br>Yes, I'm a friend of Jenny's", "leftComment": "completely unnatural"}],
[["0-6", 2], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["areafriend.wav"]}, "html": "You are at a party and everyone is talking about Jenny. Someone asks you:<br>You're a friend of Jenny's?<br>Yes, I'm not a friend of Jenny's", "leftComment": "completely unnatural"}],
[["0-7", 2], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["areafriend.wav"]}, "html": "You are at a party and everyone is talking about Jenny. Someone asks you:<br>You're a friend of Jenny's?<br>No, I'm a friend of Jenny's.", "leftComment": "completely unnatural"}],
[["0-8", 2], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["areafriend.wav"]}, "html": "You are at a party and everyone is talking about Jenny. Someone asks you:<br>You're a friend of Jenny's?<br>No, I'm not a friend of Jenny's", "leftComment": "completely unnatural"}],
[["0-1", 4], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["notplay.wav"]}, "html": "You recently arrived for your first year of college, and you are at the first practice for the club hockey team. Someone asks you:<br>You didn't play on the hockey team in high school?<br>Yes, I played on the hockey team", "leftComment": "completely unnatural"}],
[["0-2", 4], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["notplay.wav"]}, "html": "You recently arrived for your first year of college, and you are at the first practice for the club hockey team. Someone asks you:<br>You didn't play on the hockey team in high school?<br>Yes, I didn't play on the hockey team", "leftComment": "completely unnatural"}],
[["0-3", 4], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["notplay.wav"]}, "html": "You recently arrived for your first year of college, and you are at the first practice for the club hockey team. Someone asks you:<br>You didn't play on the hockey team in high school?<br>No, I played on the hockey team", "leftComment": "completely unnatural"}],
[["0-4", 4], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["notplay.wav"]}, "html": "You recently arrived for your first year of college, and you are at the first practice for the club hockey team. Someone asks you:<br>You didn't play on the hockey team in high school?<br>No, I didn't play on the hockey team", "leftComment": "completely unnatural"}],
[["0-5", 4], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["play.wav"]}, "html": "You recently arrived for your first year of college, and you are at the first practice for the club hockey team. Someone asks you:<br>You played on the hockey team in high school?<br>Yes, I played on the hockey team", "leftComment": "completely unnatural"}],
[["0-6", 4], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["play.wav"]}, "html": "You recently arrived for your first year of college, and you are at the first practice for the club hockey team. Someone asks you:<br>You played on the hockey team in high school?<br>Yes, I didn't play on the hockey team", "leftComment": "completely unnatural"}],
[["0-7", 4], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["play.wav"]}, "html": "You recently arrived for your first year of college, and you are at the first practice for the club hockey team. Someone asks you:<br>You played on the hockey team in high school?<br>No, I played on the hockey team", "leftComment": "completely unnatural"}],
[["0-8", 4], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["play.wav"]}, "html": "You recently arrived for your first year of college, and you are at the first practice for the club hockey team. Someone asks you:<br>You played on the hockey team in high school?<br>No, I didn't play on the hockey team", "leftComment": "completely unnatural"}],
[["0-1", 6], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["notbuy.wav"]}, "html": "You and your friend are grocery shopping. Your friend asks you:<br>You're not going to buy the tuna?<br>Yes, I'm going to buy it", "leftComment": "completely unnatural"}],
[["0-2", 6], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["notbuy.wav"]}, "html": "You and your friend are grocery shopping. Your friend asks you:<br>You're not going to buy the tuna?<br>Yes, I'm not going to buy it", "leftComment": "completely unnatural"}],
[["0-3", 6], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["notbuy.wav"]}, "html": "You and your friend are grocery shopping. Your friend asks you:<br>You're not going to buy the tuna?<br>No, I'm going to buy it", "leftComment": "completely unnatural"}],
[["0-4", 6], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["notbuy.wav"]}, "html": "You and your friend are grocery shopping. Your friend asks you:<br>You're not going to buy the tuna?<br>No, I'm not going to buy it", "leftComment": "completely unnatural"}],
[["0-5", 6], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["buy.wav"]}, "html": "You and your friend are grocery shopping. Your friend asks you:<br>You're going to buy the tuna?<br>Yes, I'm going to buy it", "leftComment": "completely unnatural"}],
[["0-6", 6], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["buy.wav"]}, "html": "You and your friend are grocery shopping. Your friend asks you:<br>You're going to buy the tuna?<br>Yes, I'm not going to buy it", "leftComment": "completely unnatural"}],
[["0-7", 6], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["buy.wav"]}, "html": "You and your friend are grocery shopping. Your friend asks you:<br>You're going to buy the tuna?<br>No, I'm going to buy it", "leftComment": "completely unnatural"}],
[["0-8", 6], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["buy.wav"]}, "html": "You and your friend are grocery shopping. Your friend asks you:<br>You're going to buy the tuna?<br>No, I'm not going to buy it", "leftComment": "completely unnatural"}],
[["0-1", 8], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["notlike.wav"]}, "html": "You and your new roommate are getting to know one another. He asks you:<br>You don't like movies?<br>Yes, I like movies", "leftComment": "completely unnatural"}],
[["0-2", 8], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["notlike.wav"]}, "html": "You and your new roommate are getting to know one another. He asks you:<br>You don't like movies?<br>Yes, I don't like movies", "leftComment": "completely unnatural"}],
[["0-3", 8], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["notlike.wav"]}, "html": "You and your new roommate are getting to know one another. He asks you:<br>You don't like movies?<br>No, I like movies", "leftComment": "completely unnatural"}],
[["0-4", 8], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["notlike.wav"]}, "html": "You and your new roommate are getting to know one another. He asks you:<br>You don't like movies?<br>No, I don't like movies", "leftComment": "completely unnatural"}],
[["0-5", 8], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["like.wav"]}, "html": "You and your new roommate are getting to know one another. He asks you:<br>You like movies?<br>Yes, I like movies", "leftComment": "completely unnatural"}],
[["0-6", 8], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["like.wav"]}, "html": "You and your new roommate are getting to know one another. He asks you:<br>You like movies?<br>Yes, I don't like movies", "leftComment": "completely unnatural"}],
[["0-7", 8], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["like.wav"]}, "html": "You and your new roommate are getting to know one another. He asks you:<br>You like movies?<br>No, I like movies", "leftComment": "completely unnatural"}],
[["0-8", 8], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["like.wav"]}, "html": "You and your new roommate are getting to know one another. He asks you:<br>You like movies?<br>No, I don't like movies", "leftComment": "completely unnatural"}],
[["0-1", 10], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["notcoming.wav"]}, "html": "You're at work, and your coworker is heading to the conference room to hear the boss's presentation. He asks you:<br>You're not coming to the presentation?<br>Yes, I'm coming to the presentation", "leftComment": "completely unnatural"}],
[["0-2", 10], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["notcoming.wav"]}, "html": "You're at work, and your coworker is heading to the conference room to hear the boss's presentation. He asks you:<br>You're not coming to the presentation?<br>Yes, I'm not coming to the presentation", "leftComment": "completely unnatural"}],
[["0-3", 10], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["notcoming.wav"]}, "html": "You're at work, and your coworker is heading to the conference room to hear the boss's presentation. He asks you:<br>You're not coming to the presentation?<br>No, I'm coming to the presentation", "leftComment": "completely unnatural"}],
[["0-4", 10], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["notcoming.wav"]}, "html": "You're at work, and your coworker is heading to the conference room to hear the boss's presentation. He asks you:<br>You're not coming to the presentation?<br>No, I'm not coming to the presentation", "leftComment": "completely unnatural"}],
[["0-5", 10], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["coming.wav"]}, "html": "You're at work, and your coworker is heading to the conference room to hear the boss's presentation. He asks you:<br>You're coming to the presentation?<br>Yes, I'm coming to the presentation", "leftComment": "completely unnatural"}],
[["0-6", 10], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["coming.wav"]}, "html": "You're at work, and your coworker is heading to the conference room to hear the boss's presentation. He asks you:<br>You're coming to the presentation?<br>Yes, I'm not coming to the presentation", "leftComment": "completely unnatural"}],
[["0-7", 10], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["coming.wav"]}, "html": "You're at work, and your coworker is heading to the conference room to hear the boss's presentation. He asks you:<br>You're coming to the presentation?<br>No, I'm coming to the presentation", "leftComment": "completely unnatural"}],
[["0-8", 10], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["coming.wav"]}, "html": "You're at work, and your coworker is heading to the conference room to hear the boss's presentation. He asks you:<br>You're coming to the presentation?<br>No, I'm not coming to the presentation", "leftComment": "completely unnatural"}],
[["0-1", 12], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["nottake.wav"]}, "html": "Your roommate just got home from work. He asks you:<br>You didn't take the trash out?<br>Yes, I took the trash out", "leftComment": "completely unnatural"}],
[["0-2", 12], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["nottake.wav"]}, "html": "Your roommate just got home from work. He asks you:<br>You didn't take the trash out?<br>Yes, I didn't take the trash out", "leftComment": "completely unnatural"}],
[["0-3", 12], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["nottake.wav"]}, "html": "Your roommate just got home from work. He asks you:<br>You didn't take the trash out?<br>No, I took the trash out", "leftComment": "completely unnatural"}],
[["0-4", 12], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["nottake.wav"]}, "html": "Your roommate just got home from work. He asks you:<br>You didn't take the trash out?<br>No, I didn't take the trash out", "leftComment": "completely unnatural"}],
[["0-5", 12], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["took.wav"]}, "html": "Your roommate just got home from work. He asks you:<br>You took the trash out?<br>Yes, I took the trash out", "leftComment": "completely unnatural"}],
[["0-6", 12], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["took.wav"]}, "html": "Your roommate just got home from work. He asks you:<br>You took the trash out?<br>Yes, I didn't take the trash out", "leftComment": "completely unnatural"}],
[["0-7", 12], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["took.wav"]}, "html": "Your roommate just got home from work. He asks you:<br>You took the trash out?<br>No, I took the trash out", "leftComment": "completely unnatural"}],
[["0-8", 12], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["took.wav"]}, "html": "Your roommate just got home from work. He asks you:<br>You took the trash out?<br>No, I didn't take the trash out", "leftComment": "completely unnatural"}],
[["0-1", 14], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["notemployee.wav"]}, "html": "You are at the hardware store. A person walks up to you and asks:<br>You're not an employee here?<br>Yes, I'm an employee here", "leftComment": "completely unnatural"}],
[["0-2", 14], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["notemployee.wav"]}, "html": "You are at the hardware store. A person walks up to you and asks:<br>You're not an employee here?<br>Yes, I'm not an employee here", "leftComment": "completely unnatural"}],
[["0-3", 14], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["notemployee.wav"]}, "html": "You are at the hardware store. A person walks up to you and asks:<br>You're not an employee here?<br>No, I'm an employee here", "leftComment": "completely unnatural"}],
[["0-4", 14], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["notemployee.wav"]}, "html": "You are at the hardware store. A person walks up to you and asks:<br>You're not an employee here?<br>No, I'm not an employee here", "leftComment": "completely unnatural"}],
[["0-5", 14], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["employee.wav"]}, "html": "You are at the hardware store. A person walks up to you and asks:<br>You're an employee here?<br>Yes, I'm an employee here", "leftComment": "completely unnatural"}],
[["0-6", 14], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["employee.wav"]}, "html": "You are at the hardware store. A person walks up to you and asks:<br>You're an employee here?<br>Yes, I'm not an employee here", "leftComment": "completely unnatural"}],
[["0-7", 14], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["employee.wav"]}, "html": "You are at the hardware store. A person walks up to you and asks:<br>You're an employee here?<br>No, I'm an employee here", "leftComment": "completely unnatural"}],
[["0-8", 14], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["employee.wav"]}, "html": "You are at the hardware store. A person walks up to you and asks:<br>You're an employee here?<br>No, I'm not an employee here", "leftComment": "completely unnatural"}],
[["0-1", 16], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["notdrink.wav"]}, "html": "You are at a party. The host asks you:<br>You don't drink alcohol?<br>Yes, I drink alcohol", "leftComment": "completely unnatural"}],
[["0-2", 16], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["notdrink.wav"]}, "html": "You are at a party. The host asks you:<br>You don't drink alcohol?<br>Yes, I don't drink alcohol", "leftComment": "completely unnatural"}],
[["0-3", 16], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["notdrink.wav"]}, "html": "You are at a party. The host asks you:<br>You don't drink alcohol?<br>No, I drink alcohol", "leftComment": "completely unnatural"}],
[["0-4", 16], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["notdrink.wav"]}, "html": "You are at a party. The host asks you:<br>You don't drink alcohol?<br>No, I don't drink alcohol", "leftComment": "completely unnatural"}],
[["0-5", 16], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["drink.wav"]}, "html": "You are at a party. The host asks you:<br>You drink alcohol?<br>Yes, I drink alcohol", "leftComment": "completely unnatural"}],
[["0-6", 16], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["drink.wav"]}, "html": "You are at a party. The host asks you:<br>You drink alcohol?<br>Yes, I don't drink alcohol", "leftComment": "completely unnatural"}],
[["0-7", 16], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["drink.wav"]}, "html": "You are at a party. The host asks you:<br>You drink alcohol?<br>No, I drink alcohol", "leftComment": "completely unnatural"}],
[["0-8", 16], "AJ", {"q": "Please indicate how natural this response seems on a scale of 1 to 8 ", "rightComment": "completely natural).", "s": {"audio": ["drink.wav"]}, "html": "You are at a party. The host asks you:<br>You drink alcohol?<br>No, I don't drink alcohol", "leftComment": "completely unnatural"}]
];
